eval_cfgs:
  # The deepspeed configuration
  ds_cfgs: ds_z3_config.json
  vllm_cfgs: vllm_basic.json

default:
  # evaluation configurations
  eval_cfgs:
    # Output directory name
    output_dir: null
    # Num shot
    n_shot: 0
    # Use Chain of Thought
    cot: false
  # Configuration for data
  data_cfgs:
    # Task name
    task: hellaswag
    # Task directory
    task_dir: Rowan/hellaswag
    # Evaluation split
    split: validation

  # Model configurations
  model_cfgs:
    model_id: Meta-Llama-3-8B-Instruct
    # Pretrained model name or path
    model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
    # Chat template
    chat_template: Llama3
    # The max token length
    model_max_length: 2048
